version: '3.7'

services:
  nginx:
    container_name: nginx-shortURL
    image: nginx:1.25.2
    restart: unless-stopped
    volumes:
      - ../app:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8080:80
    environment:
      - NGINX_PORT=80
    depends_on:
      - php

  php:
    build:
#      context: .
      dockerfile: ./php/Dockerfile
    container_name: php-shortURL
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - ../app:/var/www/html

  mysql:
#    image: mysql:8.0
    container_name: mysql-shortURL
    build:
      dockerfile: ./mysql/Dockerfile
    restart: always
    volumes:
      - ./mysql/conf/my.cnf:/etc/my.cnf
      - ../db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: shortURL
      MYSQL_PASSWORD: shortURLpw
      MYSQL_DATABASE: shortURL
    ports:
      - 33061:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
